"""init_tables

Revision ID: 573891a7f740
Revises: 
Create Date: 2026-05-24 21:50:15.350875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '573891a7f740'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.String(length=32), nullable=False, comment='UUID hex (32 chars)'),
    sa.Column('target_product', sa.String(length=500), nullable=False, comment='Product name to analyze'),
    sa.Column('analysis_dimensions', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='e.g. {pricing: true, features: true}'),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='task_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False, comment='planner | research | analysis | writer | reviewer'),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='started | completed | error | progress'),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Per-agent execution trace for observability and timeline replay'
    )
    op.create_index(op.f('ix_execution_logs_task_id'), 'execution_logs', ['task_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('structured_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('metric_cards', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('quality_feedback', sa.Text(), nullable=True),
    sa.Column('citations_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('token_usage', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_task_id'), 'reports', ['task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_task_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_execution_logs_task_id'), table_name='execution_logs')
    op.drop_table('execution_logs')
    op.drop_table('tasks')
    # ### end Alembic commands ###
